development:
  stripe_secret_key: 'sk_test_51LkSemIAoVNpf06EtqdiuopHgn9vtswsq1C3cMQVybUFhMouPjed7xtKTaDO6j0FtMbcMhTMLN3ESGJrNDoB0ENG00rOgTKCl8'
  stripe_publishable_key: 'pk_test_51LkSemIAoVNpf06EFIhAvyj8gWFozg9iRbV2gTWtR5LdsWT3iaFcQYWgDq8AHSRDHyHbk1S28wd4c4Y3XdOr8b3N00zit1fsCn'
